/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.9/samples
 */

tasks.register("buildAll") {
    dependsOn(gradle.includedBuilds.map { it.task(":${it.name}:build") })
}

tasks.register("publishAllToMavenLocal") {
    dependsOn(gradle.includedBuilds.map { it.task(":${it.name}:publishToMavenLocal") })
}

// Publishes into `maven/` at the repo root, which is served over
// raw.githubusercontent.com so consumers need nothing in ~/.m2.
tasks.register("publishAllToRepoDir") {
    dependsOn(gradle.includedBuilds.map {
        it.task(":${it.name}:publishAllPublicationsToRepoDirRepository")
    })
}